import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  type PortkeyPricingFile,
  type PortkeyPricingFileIndexEntry,
  transformPortkeyPricingCatalog
} from "../apps/server/src/pricing-catalog-transform.js";

const INDEX_URL = "https://api.github.com/repos/Portkey-AI/models/contents/pricing";
const OUTPUT_PATH = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../apps/server/src/generated/pricing-catalog.ts");

async function fetchJson<T>(url: string): Promise<T> {
  const response = await fetch(url, {
    headers: {
      Accept: "application/vnd.github+json",
      "User-Agent": "agentic-insights-sync"
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }

  return (await response.json()) as T;
}

function formatGeneratedModule(source: unknown): string {
  return `// This file is generated by scripts/sync-pricing-catalog.ts.\n// Source: https://github.com/Portkey-AI/models (MIT)\n\nimport type { GeneratedPricingCatalog } from "../pricing-catalog-transform.js";\n\nexport const GENERATED_PRICING_CATALOG: GeneratedPricingCatalog = ${JSON.stringify(
    source,
    null,
    2
  )} as const;\n`;
}

async function main() {
  const indexEntries = await fetchJson<PortkeyPricingFileIndexEntry[]>(INDEX_URL);
  const pricingFiles = new Map<string, PortkeyPricingFile>();

  for (const entry of indexEntries) {
    if (entry.type !== "file" || !entry.download_url || !entry.name.endsWith(".json")) {
      continue;
    }

    pricingFiles.set(entry.name, await fetchJson<PortkeyPricingFile>(entry.download_url));
  }

  const catalog = transformPortkeyPricingCatalog(indexEntries, pricingFiles, new Date().toISOString());
  await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await fs.writeFile(OUTPUT_PATH, formatGeneratedModule(catalog));

  process.stdout.write(
    `Wrote ${catalog.entries.length} pricing entries across ${catalog.providerSources.length} providers to ${OUTPUT_PATH}\n`
  );
}

void main().catch((error) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
